/**
 * Generate a plain-text parent/teacher report from student metrics.
 * @param {Object} metrics - Output of computeMetrics()
 * @param {Object} options - { studentName, dateRange, streakData, masteryLevels, totalTimeSpent }
 * @returns {string} Plain-text report suitable for pasting into messages/emails
 */
export function generateReport(metrics, options = {}) {
  const {
    studentName = 'Student',
    dateRange = '',
    streakData = null,
    masteryLevels = {},
    totalTimeSpent = null,
  } = options;

  const lines = [];

  // Header
  lines.push('=== ALGEBRA ASSAULT - LEARNING REPORT ===');
  lines.push('');
  lines.push(`Student: ${studentName}`);
  if (dateRange) lines.push(`Period: ${dateRange}`);
  lines.push(`Generated: ${new Date().toLocaleDateString()}`);
  lines.push('');

  // Overview
  lines.push('--- OVERVIEW ---');
  if (metrics) {
    lines.push(`Overall Accuracy: ${metrics.overallAccuracy != null ? metrics.overallAccuracy.toFixed(1) + '%' : 'N/A'}`);
    lines.push(`Total Questions Solved: ${metrics.totalQuestions || 0}`);
    if (totalTimeSpent != null) {
      const mins = Math.round(totalTimeSpent / 60);
      lines.push(`Total Time Spent: ${mins} minutes`);
    }
  } else {
    lines.push('No progress data available.');
  }
  lines.push('');

  // Topics Covered
  lines.push('--- TOPICS COVERED ---');
  if (metrics && metrics.perTopicAccuracy) {
    const entries = Object.entries(metrics.perTopicAccuracy);
    if (entries.length > 0) {
      for (const [topic, accuracy] of entries) {
        const mastery = masteryLevels[topic] || 'none';
        const masteryLabel = mastery !== 'none' ? ` [${mastery.toUpperCase()}]` : '';
        lines.push(`  ${topic}: ${accuracy.toFixed(1)}%${masteryLabel}`);
      }
    } else {
      lines.push('  No topic data recorded yet.');
    }
  } else {
    lines.push('  No topic data recorded yet.');
  }
  lines.push('');

  // Strengths & Improvement
  lines.push('--- STRENGTHS & AREAS FOR IMPROVEMENT ---');
  if (metrics) {
    if (metrics.strongestTopic) {
      lines.push(`  Strongest: ${metrics.strongestTopic} (${(metrics.perTopicAccuracy[metrics.strongestTopic] || 0).toFixed(0)}%)`);
    }
    if (metrics.weakestTopic) {
      lines.push(`  Needs Work: ${metrics.weakestTopic} (${(metrics.perTopicAccuracy[metrics.weakestTopic] || 0).toFixed(0)}%)`);
    }
    if (metrics.trend) {
      const diff = metrics.trend.newer - metrics.trend.older;
      if (diff > 0) {
        lines.push(`  Trend: Improving (+${diff.toFixed(1)}%)`);
      } else if (diff < 0) {
        lines.push(`  Trend: Declining (${diff.toFixed(1)}%)`);
      } else {
        lines.push('  Trend: Steady');
      }
    }
  }
  lines.push('');

  // Engagement
  lines.push('--- ENGAGEMENT ---');
  if (streakData && streakData.currentStreak > 0) {
    lines.push(`  Daily Challenge Streak: ${streakData.currentStreak} day${streakData.currentStreak !== 1 ? 's' : ''}`);
  }
  if (metrics && metrics.totalQuestions > 0) {
    lines.push(`  Sessions Completed: ${metrics.sessionsCount || 'N/A'}`);
  }
  lines.push('');

  lines.push('--- END OF REPORT ---');
  lines.push('Generated by Algebra Assault (MathCoach)');

  return lines.join('\n');
}
